spring.application.name=task-manager-dev

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/my_db_jeet

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.enabled=True

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# commented it as it will be auto detetected by spring boot , this dialects only needs if working with older version of db's

